name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # 1. Check out the repo
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the Gatsby site
      - name: Build Gatsby
        run: npm run build

      # 5. Deploy to S3
      # IAM User has the least privileges possible to use s3-deploy@v4
      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: 'public'
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true
          no-cache: true
          files-to-include: '{.*/**,**}'
